version: '3.7'

services:
  pihole:
    container_name: pihole
#    image: cbcrowe/pihole-unbound:latest
    image: kwizatz/pihole-unbound:latest
    hostname: pihole
    domainname: pihole.local
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 5335:5335/tcp 
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.5.195
      - TZ=America/Sao_Paulo
      - WEBPASSWORD=senha@123
      - WEBTHEME=default-light
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.5.1
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_CIDR=192.168.0.0/16
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC=true
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: always
    networks:
      pihole:

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
  pihole:

